### ISSUE TITLE
Add maven wrapper

### ISSUE THREAD

**Issue by japzio** [cerus/deploy-helper#12]
# Contribution request

## Type
New feature

## Changes
*.Add maven wrapper https://maven.apache.org/wrapper/. To be able to run maven if not installed locally*

## Relevant issues
n/a

**Comment by cerus** [comment]
Accepted, have fun! Please make sure to follow the [contribution guidelines](https://github.com/cerus/deploy-helper/blob/master/CONTRIBUTING.md) :)

(In regards to rule 1: you don't need to create an issue since this one already exists.)

**Comment by cerus** [comment]
Done in #13
