### ISSUE TITLE
Make configuration more extendable

### ISSUE THREAD

**Issue by lus** [cerus/deploy-helper#8]
# Contribution request

## Type
- [x] New feature
- [ ] Bugfix
- [ ] Documentation

## Changes
Currently, you are only able to define exactly one SSH config per config file. This is not extendable and will not allow you to define more than one SSH host (for example if you have multiple destinations) with different credentials.

Also the current system does not allow proper extension of deployment tasks as the config relies on SSH and command executions.

## Relevant issues
This issue will be worked on together with #5 as it is intuitive to do so.

**Comment by cerus** [comment]
Request approved. Please make sure to follow the [contribution guidelines](https://github.com/cerus/deploy-helper/blob/master/CONTRIBUTING.md) :)

**Comment by cerus** [comment]
Any updates?

**Comment by lus** [comment]
Would you like to write me a physical letter next time so I can read your message even more difficult?
Or use a telegram?
Or morse-code?

**Comment by cerus** [comment]
I'm just trying to reach out to you about the status of your pr mate

**Comment by lus** [comment]
Just message me on Discord like you do with every other unimportant thing.

**Comment by cerus** [comment]
I thought I'd get a response that's not "I'll work on it next weekend" on here, and it seems like I was right 🤔

**Comment by lus** [comment]
I'll work on it next weekend.

**Comment by lus** [comment]
That aged well

**Comment by cerus** [comment]
Not gonna lie, I've given up hope on this one

**Comment by cerus** [comment]
![Gif](https://c.tenor.com/oUvaabzjR3gAAAAC/rip-coffin.gif)
